config/routes.rb
Web::Application.routes.draw do
 
  resources :orcamentos
  
  resources :orcamentos do
    resources :sub_orcamentos
  end

  resources :caixas

  resources :patrocinios

  get "sessions/new"

  resources :utilizadors
  resources :sessions, :only => [:new, :create, :destroy]

  resources :grupos
  
  match '/signout', :to => 'sessions#destroy'
  match '/estatisticas', :to =>'estatisticas#main'
  match '/estatisticas/relatorio', :to => 'estatisticas#relatorio'
     
  get "home/index"

     root :to => 'sessions#new'

end

app/models/patrocinio.rb
class Patrocinio < ActiveRecord::Base
  belongs_to :utilizador
  
  validates :nome, :presence => true, :uniqueness => true
  validates_numericality_of :valor, :greater_than => 0
  validate :inicio_before_fim

  has_attached_file :photo, :styles => {:small => "200x200>"},
                    :url => "/system/:attachment/:nome/:style/:filename",
                    :path => ":rails_root/public/system/:attachment/:nome/:style/:filename"

  def inicio_before_fim
    return unless datainicio and datafim
    errors.add(:datainicio, "precisa de ser anterior a datafim") unless datainicio < datafim
  end
end

app/controllers/patrocinios_controller.rb
class PatrociniosController < ApplicationController

  @@filter_id = 0
  before_filter :authenticate, :only => [:index, :show, :new, :edit, :update, :destroy]
  before_filter :estatuto_drepAdmin, :only => [:index, :show, :destroy]
  before_filter :grupo_drep, :only => [:new, :edit, :update]
  after_filter :httplink, :only => [:create, :update]
  
  def httplink
    @patrocinio = Patrocinio.find(@@filter_id)
    (@patrocinio.link = ("http://" << @patrocinio.link)) unless ((@patrocinio.link).include? "http://") || (@patrocinio.link).empty?
    @patrocinio.save
  end

  def estatuto_drepAdmin
    redirect_to utilizadors_path, notice: "Apenas administradores ou utilizadores pertencentes ao DREP!" unless grupo_drep? || estatuto_admin?
  end

  def grupo_drep
    redirect_to utilizadors_path, notice: "Apenas administradores ou utilizadores pertencentes ao DREP!" unless grupo_drep? || estatuto_admin?
  end

  # GET /patrocinios
  # GET /patrocinios.json
  def index
    @patrocinios = Patrocinio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patrocinios }
    end
  end

  # GET /patrocinios/1
  # GET /patrocinios/1.json
  def show
    @patrocinio = Patrocinio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patrocinio }
    end
  end

  # GET /patrocinios/new
  # GET /patrocinios/new.json
  def new
    @patrocinio = Patrocinio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @patrocinio }
    end
  end

  # GET /patrocinios/1/edit
  def edit
    @patrocinio = Patrocinio.find(params[:id])
  end

  # POST /patrocinios
  # POST /patrocinios.json
  def create
    @utilizador = Utilizador.find(current_utilizador.id)
    @patrocinio = @utilizador.patrocinios.build(params[:patrocinio])

    respond_to do |format|
      if @patrocinio.save
        @@filter_id = @patrocinio.id
        format.html { redirect_to @patrocinio, notice: 'Patrocinio was successfully created.' }
        format.json { render json: @patrocinio, status: :created, location: @patrocinio }
      else
        format.html { render action: "new" }
        format.json { render json: @patrocinio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patrocinios/1
  # PUT /patrocinios/1.json
  def update
    @patrocinio = Patrocinio.find(params[:id])

    respond_to do |format|
      if @patrocinio.update_attributes(params[:patrocinio])
        @@filter_id = @patrocinio.id
        format.html { redirect_to @patrocinio, notice: 'Patrocinio was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @patrocinio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patrocinios/1
  # DELETE /patrocinios/1.json
  def destroy
    @patrocinio = Patrocinio.find(params[:id])
    @patrocinio.destroy

    respond_to do |format|
      format.html { redirect_to patrocinios_url }
      format.json { head :ok }
    end
  end

  def authenticate
    deny_access unless signed_in?
  end
end

app/helpers/patrocinios_helper.rb
module PatrociniosHelper
end

app/views/patrocinios/_form.html.erb
<%= form_for @patrocinio, :html => {:multipart => true}  do |f| %>
  <% if @patrocinio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patrocinio.errors.count, "error") %> prohibited this patrocinio from being saved:</h2>

      <ul>
      <% @patrocinio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label "Descrição" %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :valor %><br />
    <%= f.text_field :valor %> €
  </div>
  <div class="field">
    <%= f.label "Data de Início" %><br />
    <%= f.date_select :datainicio %>
  </div>
  <div class="field">
    <%= f.label "Data Final" %><br />
    <%= f.date_select :datafim %>
  </div>
  <div class="field">
    <%= f.label :link %><br/>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label "Logotipo" %><br/>
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patrocinios/edit.html.erb
<h1>Editar Patrocínio</h1>

<%= render 'form' %>

<p align="center">
<%= link_to 'Mostrar', @patrocinio %> |
<%= link_to 'Retroceder', patrocinios_path %>
</p>

app/views/patrocinios/index.html.erb
<h1 align="center">Registos de Patrocínios</h1>
<p id="notice"><%= notice %></p>

<% if grupo_drep? || estatuto_admin? %>
	<%= link_to 'Novo Patrocínio', new_patrocinio_path, :class => 'signup_button round' %>
<% end %>

<table>
  <tr>
    <th>Nome</th>
    <th>Descrição</th>
    <th>Valor</th>
    <th>Data de Início</th>
    <th>Data Final</th>
    <th>Utilizador</th>
  </tr>

<% @patrocinios.each do |patrocinio| %>
  <tr>
    <td><%= patrocinio.nome %></td>
    <td><%= patrocinio.descricao %></td>
    <td><%= patrocinio.valor %> €</td>
    <td><%= patrocinio.datainicio %></td>
    <td><%= patrocinio.datafim %></td>
    <% if Utilizador.find_by_id(patrocinio.utilizador_id).nil? %>
      <td> Inexistente </td>
    <% else %>
      <td><%= Utilizador.find_by_id(patrocinio.utilizador_id).nome %></td>
    <% end %>
    <td><%= link_to image_tag("search.png", :border=>0), patrocinio %></td>
    <% if grupo_drep? %>
      <td><%= link_to image_tag("edit.png", :border=>0), edit_patrocinio_path(patrocinio) %></td>
    <% end %>
    <td><%= link_to image_tag("destroy.png", :border=>0), patrocinio, confirm: 'Tem a certeza?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/patrocinios/new.html.erb
<h1>Novo Patrocínio</h1>

<%= render 'form' %>

<p align="center">
<%= link_to 'Retroceder', patrocinios_path %>
</p>

app/views/patrocinios/show.html.erb
<p id="notice"><%= notice %></p>

<% if @patrocinio.photo? %>
<p>
  <%= image_tag @patrocinio.photo.url (:small) %>
</p>
<% end %>

<p>
  <b>Nome:</b>
  <%= @patrocinio.nome %>
</p>

<p>
  <b>Descrição:</b>
  <%= @patrocinio.descricao %>
</p>

<p>
  <b>Valor:</b>
  <%= @patrocinio.valor %> €
</p>

<p>
  <b>Link Oficial:</b>
  <%= link_to @patrocinio.link, @patrocinio.link, :target => "_blank" %>
</p>

<p>
  <b>Data de Início:</b>
  <%= @patrocinio.datainicio %>
</p>

<p>
  <b>Data Finaç:</b>
  <%= @patrocinio.datafim %>
</p>

<p>
<b>Utilizador:</b>
<% if Utilizador.find_by_id(@patrocinio.utilizador_id).nil? %>
  Inexistente
<% else %>
  <%= Utilizador.find(@patrocinio.utilizador_id).nome %>
<% end %>
</p>

<p align="center">
<% if grupo_drep? %>
  <%= link_to 'Editar', edit_patrocinio_path(@patrocinio) %> |
<% end %>
<%= link_to 'Retroceder', patrocinios_path %>
</p>