config/routes.rb
Web::Application.routes.draw do
 
  resources :orcamentos
  
  resources :orcamentos do
    resources :sub_orcamentos
  end

  resources :caixas

  resources :patrocinios

  get "sessions/new"

  resources :utilizadors
  resources :sessions, :only => [:new, :create, :destroy]

  resources :grupos
  
  match '/signout', :to => 'sessions#destroy'
  match '/estatisticas', :to =>'estatisticas#main'
  match '/estatisticas/relatorio', :to => 'estatisticas#relatorio'
     
  get "home/index"

     root :to => 'sessions#new'

end

app/models/orcamento.rb
class Orcamento < ActiveRecord::Base
  belongs_to :grupo
  has_many :sub_orcamentos, :dependent => :destroy

  validates :nome, :presence => true, :uniqueness => true
  validates :data, :presence => true
end

app/controllers/orcamentos_controller.rb
class OrcamentosController < ApplicationController

  before_filter :authenticate, :only => [:new, :show, :index, :edit, :update, :destroy]
  before_filter :estatuto_admin, :only => [:destroy]
  before_filter :grupo_correcto, :only => [:show, :edit, :update]

  def estatuto_admin
    redirect_to orcamentos_path, notice: "Precisa de ser administrador!" unless estatuto_admin?
  end

  def grupo_correcto
    @grupo = Grupo.find(current_utilizador.grupo_id)
    @orcamento = @grupo.orcamentos.find_by_id(params[:id])
    redirect_to orcamentos_path, notice: "Precisa de ser administrador ou de pertencer ao grupo que propos o orcamento" if @orcamento.nil? && !estatuto_admin?
  end

  # GET /orcamentos
  # GET /orcamentos.json
  def index
    if (estatuto_admin?)
     @orcamentos = Orcamento.all

     respond_to do |format|
       format.html # index.html.erb
       format.json { render json: @orcamentos }
    end
    else
      @orcamentos = Orcamento.find_all_by_grupo_id(current_utilizador.grupo_id)

      respond_to do |format|
        format.html
        format.json { render json: @orcamentos }
      end
    end
  end

  # GET /orcamentos/1
  # GET /orcamentos/1.json
  def show
    @orcamento = Orcamento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @orcamento }
    end
  end

  # GET /orcamentos/new
  # GET /orcamentos/new.json
  def new
    @orcamento = Orcamento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @orcamento }
    end
  end

  # GET /orcamentos/1/edit
  def edit
    @orcamento = Orcamento.find(params[:id])
  end

  # POST /orcamentos
  # POST /orcamentos.json
  def create
    @grupo = Grupo.find(current_utilizador.grupo_id)
    @orcamento = @grupo.orcamentos.build(params[:orcamento])

    respond_to do |format|
      if @orcamento.save
        format.html { redirect_to @orcamento, notice: 'Orcamento was successfully created.' }
        format.json { render json: @orcamento, status: :created, location: @orcamento }
      else
        format.html { render action: "new" }
        format.json { render json: @orcamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orcamentos/1
  # PUT /orcamentos/1.json
  def update
    @orcamento = Orcamento.find(params[:id])

    respond_to do |format|
      if @orcamento.update_attributes(params[:orcamento])
        format.html { redirect_to @orcamento, notice: 'Orcamento was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @orcamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orcamentos/1
  # DELETE /orcamentos/1.json
  def destroy
    @orcamento = Orcamento.find(params[:id])
    @orcamento.destroy

    respond_to do |format|
      format.html { redirect_to orcamentos_url }
      format.json { head :ok }
    end
  end

  def authenticate
    deny_access unless signed_in?
  end
end

app/helpers/orcamentos_helper.rb
module OrcamentosHelper

  def orcamentoValorActual(orcamento)
    orcamento.valor = 0.0
    orcamento.actual = 1
    orcamento.sub_orcamentos.each do |so|
    if so.estado == "Aceite"
       orcamento.valor = orcamento.valor + so.valor
    end
    if so.estado == "Em Espera"
      orcamento.actual = 0
    end
    end
    orcamento.save
  end
end

app/views/orcamentos/_form.html.erb
<%= form_for(@orcamento) do |f| %>
  <% if @orcamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orcamento.errors.count, "error") %> prohibited this orcamento from being saved:</h2>

      <ul>
      <% @orcamento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.hidden_field :valor %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.hidden_field :actual %>
  </div>
<br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orcamentos/edit.html.erb
<h1>Editar orçamento</h1>

<%= render 'form' %>
<p align="center">
<%= link_to 'Retroceder', orcamentos_path %>
</p>

app/views/orcamentos/index.html.erb
<h1 align="center">Orcamentos</h1>
<p id="notice"><%= notice %></p>

<%= link_to 'Novo Orçamento', new_orcamento_path, :class => 'signup_button round' %>
<table>
  <tr>
    <th>Nome</th>
    <th>Descricao</th>
    <th>Valor</th>
    <th>Data</th>
    <th>Estado</th>
    <th>Grupo</th>
  </tr>

<% @orcamentos.each do |orcamento| %>
  <tr>
    <td><%= orcamento.nome %></td>
    <td><%= orcamento.descricao %></td>
    <td><%= orcamento.valor %> €</td>
    <td><%= orcamento.data %></td>
    <% if (orcamento.actual == true) %>
      <td>Actualizado</td>
    <% else %>
      <td>Desactualizado</td>
    <% end %>
    <% if Grupo.find_by_id(orcamento.grupo_id).nil? %>
	<td>Inexistente</td>
    <% else %>
    <td><%= Grupo.find(orcamento.grupo_id).nome %></td>
    <% end %>
    <td><%= link_to image_tag("search.png", :border=>0), orcamento %></td>
    <td><%= link_to image_tag("edit.png", :border=>0), edit_orcamento_path(orcamento) %></td>
    <% if estatuto_admin? %>
      <td><%= link_to image_tag("destroy.png", :border=>0), orcamento, confirm: 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/orcamentos/new.html.erb
<h1>Novo orçamento</h1>

<%= render 'form' %>

<p align="center">
<%= link_to 'Retroceder', orcamentos_path %>
<p>

app/views/orcamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @orcamento.nome %>
</p>

<p>
  <b>Descricao:</b>
  <%= @orcamento.descricao %>
</p>

<p>
  <b>Valor:</b>
  <%= @orcamento.valor %> € 
</p>

<p>
  <b>Data:</b>
  <%= @orcamento.data %>
</p>

<p>
  <b>Estado:</b>
  <% if @orcamento.actual == true %>
    Actualizado
  <% else %>
    Desactualizado
  <% end %>
</p>

<p>
  <b>Grupo:</b>
  <% if Grupo.find_by_id(@orcamento.grupo_id).nil? %>
	Inexistente
  <% else %>
  	<%= Grupo.find(@orcamento.grupo_id).nome %>
  <% end %>
</p>

</p>
<%= link_to 'Novo item', new_orcamento_sub_orcamento_path(@orcamento),:class => 'signup_button round' %>
<% if @orcamento.sub_orcamentos.count != 0 %>
<h2 align="center">Lista de items</h2>


<table>
  <tr>
    <th>Descricao</th>
    <th>Valor</th>
    <th>Estado</th>
    <th>Utilizador</th>
  </tr>
  <% @orcamento.sub_orcamentos.each do |so| %>
    <tr>
      <td><%= so.descricao %></td>
      <td><%= so.valor %> €</td>
      <td><%= so.estado %></td>
	<% if Utilizador.find_by_id(so.utilizador_id).nil? %>
	<td> Inexistente </td>
	<% else %>
      <td><%= Utilizador.find(so.utilizador_id).nome %></td>
	<% end %>
      <td><%= link_to image_tag("search.png", :border=>0), orcamento_sub_orcamento_path(@orcamento,so) %></td>
      <td><%= link_to image_tag("edit.png", :border=>0), edit_orcamento_sub_orcamento_path(@orcamento,so) %></td>
    </tr>
  <% end %>
</table>
<% end %>


<p align="center">
<%= link_to 'Retroceder', orcamentos_path %>
</p>