config/routes.rb
Web::Application.routes.draw do
 
  resources :orcamentos
  
  resources :orcamentos do
    resources :sub_orcamentos
  end

  resources :caixas

  resources :patrocinios

  get "sessions/new"

  resources :utilizadors
  resources :sessions, :only => [:new, :create, :destroy]

  resources :grupos
  
  match '/signout', :to => 'sessions#destroy'
  match '/estatisticas', :to =>'estatisticas#main'
  match '/estatisticas/relatorio', :to => 'estatisticas#relatorio'
     
  get "home/index"

     root :to => 'sessions#new'

end

app/models/sub_orcamento.rb
class SubOrcamento < ActiveRecord::Base
  belongs_to :orcamento
  belongs_to :utilizador

  validates :descricao, :presence => true
  validates_numericality_of :valor, :greater_than => 0
  validates :estado, :presence => true
end

app/controllers/sub_orcamentos_controller.rb
class SubOrcamentosController < ApplicationController

  before_filter :authenticate, :only => [:show, :index, :new, :edit, :update, :destroy]
  before_filter :correct_grupo, :only => [:show, :edit, :update]
  before_filter :correct_for_new, :only => [:new]
  after_filter :actualizaOrcamento, :only => [:create, :update, :destroy]

  def actualizaOrcamento  
    @orcamento = Orcamento.find_by_id(params[:orcamento_id])
    orcamentoValorActual(@orcamento)
  end

  def correct_for_new
    @grupo = Grupo.find(current_utilizador.grupo_id)
    @orcamento = @grupo.orcamentos.find_by_id(params[:orcamento_id])
    redirect_to orcamentos_path, notice: "Apenas administradores ou utilizadores pertencentes ao grupo que criou o orcamento principal" if @orcamento.nil? && !estatuto_admin?
  end

  def correct_grupo
    @grupo = Grupo.find(current_utilizador.grupo_id)
    @orcamento = @grupo.orcamentos.find_by_id(params[:orcamento_id])
    if !@orcamento.nil?
      @sub_orcamento = @orcamento.sub_orcamentos.find_by_id(params[:id])
    end
    redirect_to orcamentos_path, notice: "Apenas administradores ou utilizadores pertencentes ao grupo do orcamento principal" if @sub_orcamento.nil? && !estatuto_admin?
  end

  # GET /sub_orcamentos
  # GET /sub_orcamentos.json
  def index
    @sub_orcamentos = SubOrcamento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sub_orcamentos }
    end
  end

  # GET /sub_orcamentos/1
  # GET /sub_orcamentos/1.json
  def show
    @sub_orcamento = SubOrcamento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sub_orcamento }
    end
  end

  # GET /sub_orcamentos/new
  # GET /sub_orcamentos/new.json
  def new
    @orcamento = Orcamento.find(params[:orcamento_id])
    @sub_orcamento = SubOrcamento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sub_orcamento }
    end
  end

  # GET /sub_orcamentos/1/edit
  def edit
    @orcamento = Orcamento.find(params[:orcamento_id])
    @sub_orcamento = SubOrcamento.find(params[:id])
  end

  # POST /sub_orcamentos
  # POST /sub_orcamentos.json
  def create
    @orcamento = Orcamento.find(params[:orcamento_id])
    @sub_orcamento = @orcamento.sub_orcamentos.build(params[:sub_orcamento])
    @sub_orcamento.utilizador = current_utilizador

    respond_to do |format|
      if @sub_orcamento.save
        format.html { redirect_to orcamento_sub_orcamento_path(@orcamento,@sub_orcamento), notice: 'Sub orcamento was successfully created.' }
        format.json { render json: @sub_orcamento, status: :created, location: @sub_orcamento }
      else
        format.html { render action: "new" }
        format.json { render json: @sub_orcamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sub_orcamentos/1
  # PUT /sub_orcamentos/1.json
  def update
    @sub_orcamento = SubOrcamento.find(params[:id])
    @orcamento = Orcamento.find(params[:orcamento_id])
    
    respond_to do |format|
      if @sub_orcamento.update_attributes(params[:sub_orcamento])
        format.html { redirect_to orcamento_sub_orcamento_path(@orcamento,@sub_orcamento), notice: 'Sub orcamento was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @sub_orcamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_orcamentos/1
  # DELETE /sub_orcamentos/1.json
  def destroy
    @sub_orcamento = SubOrcamento.find(params[:id])
    @sub_orcamento.destroy

    respond_to do |format|
      format.html { redirect_to sub_orcamentos_url }
      format.json { head :ok }
    end
  end

  def authenticate
    deny_access unless signed_in?
  end
end

app/helpers/sub_orcamentos_helper.rb
module SubOrcamentosHelper
end

app/views/sub_orcamentos/_form.html.erb
<%= form_for([@orcamento, @sub_orcamento]) do |f| %>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :valor %><br />
    <%= f.text_field :valor %> €
  </div>
  <div class="field">
  <%= f.label :estado %>
  <%= select(:sub_orcamento, :estado, ["Em Espera","Aceite","Rejeitado"], {}, :disabled => !estatuto_admin?) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sub_orcamentos/edit.html.erb
<h1>Editing sub_orcamento</h1>

<%= render 'form' %>

<%= link_to 'Show', orcamento_sub_orcamento_path(@sub_orcamento.orcamento, @sub_orcamento) %> |
<%= link_to 'Back', orcamento_path(@sub_orcamento.orcamento) %>

app/views/sub_orcamentos/index.html.erb
<h1>Listing sub_orcamentos</h1>

<table>
  <tr>
    <th>Descricao</th>
    <th>Valor</th>
    <th>Estado</th>
    <th>Orcamento</th>
    <th>Utilizador</th>
  </tr>

<% @sub_orcamentos.each do |sub_orcamento| %>
  <tr>
    <td><%= sub_orcamento.descricao %></td>
    <td><%= sub_orcamento.valor %></td>
    <td><%= sub_orcamento.estado %></td>
    <td><%= sub_orcamento.orcamento %></td>
    <td><%= sub_orcamento.utilizador %></td>
    <td><%= link_to image_tag("search.png", :border=>0), sub_orcamento %></td>
    <td><%= link_to link_to image_tag("edit.png", :border=>0), edit_sub_orcamento_path(sub_orcamento) %></td>
    <td><%= link_to image_tag("destroy.png", :border=>0), sub_orcamento, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sub orcamento', new_sub_orcamento_path %>

app/views/sub_orcamentos/new.html.erb
<h1>New sub_orcamento</h1>

<%= render 'form' %>

<%= link_to 'Back', orcamento_path(@orcamento) %>

app/views/sub_orcamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Descricao:</b>
  <%= @sub_orcamento.descricao %>
</p>

<p>
  <b>Valor:</b>
  <%= @sub_orcamento.valor %> €
</p>

<p>
  <b>Estado:</b>
  <%= @sub_orcamento.estado %>
</p>

<p>
  <b>Grupo:</b>
	<% if Orcamento.find_by_id(@sub_orcamento.orcamento).nil? || Grupo.find_by_id(Orcamento.find(@sub_orcamento.orcamento).grupo).nil? %>
	Inexistente
	<% else %>
  	<%= Grupo.find(Orcamento.find(@sub_orcamento.orcamento).grupo).nome %>
	<% end %>
</p>

<p>
  <b>Utilizador:</b>
	<% if Utilizador.find_by_id(@sub_orcamento.utilizador).nil? %>
	Inexistente
	<% else %>
  <%= Utilizador.find(@sub_orcamento.utilizador).nome %>
	<% end %>
</p>


<%= link_to 'Edit', edit_orcamento_sub_orcamento_path(@sub_orcamento.orcamento, @sub_orcamento) %> |
<%= link_to 'Back', orcamento_path(@sub_orcamento.orcamento) %>