config/routes.rb
Web::Application.routes.draw do
 
  resources :orcamentos
  
  resources :orcamentos do
    resources :sub_orcamentos
  end

  resources :caixas

  resources :patrocinios

  get "sessions/new"

  resources :utilizadors
  resources :sessions, :only => [:new, :create, :destroy]

  resources :grupos
  
  match '/signout', :to => 'sessions#destroy'
  match '/estatisticas', :to =>'estatisticas#main'
  match '/estatisticas/relatorio', :to => 'estatisticas#relatorio'
     
  get "home/index"

     root :to => 'sessions#new'

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <p>Copyright © 2012 CeSIUM. All rights reserved.</p>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= image_tag("logo1.png",:size=> "150x50", :alt => "GF Núcleos ", :class => "round") %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", caixas_path %></li>
      <li><%= link_to "Ajuda", '#' %></li>
      <li><%= link_to "Sair ", signout_path, :method => :delete %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_subHeader.html.erb
<subHeader>
  <nav class="round">
    <ul>
      <% if signed_in? %>
	 <li><%= link_to "Caixa ", caixas_path %></li>        
        <li><%= link_to "Orçamentos ", orcamentos_path %></li>
        <% if estatuto_admin? || grupo_drep? %>
          <li><%= link_to "Patrocinios ", patrocinios_path %></li>
        <% end %>
        <% if estatuto_admin? %>
          <li><%= link_to "Estatisticas ", estatisticas_path %>
        <% end %>
        <li><%= link_to "Grupos ", grupos_path %></li>
	<li><%= link_to "Utilizadores ", utilizadors_path %></li>
                
	<% end %>
    </ul>
  </nav>
</subHeader>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GF Nucleos</title>
  <%= stylesheet_link_tag 'default' %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/header' %>
 <%= render 'layouts/subHeader' %>
    <section class="round">
      <%= yield %>
    </section>
      <%= render 'layouts/footer' %> 
 </div>

</body>
</html>